### ISSUE TITLE
Whois 3.4.2.1 Ruby Gem no longer available

### ISSUE THREAD

**Issue by magicknot** [ukwa/jruby-whois#1]
Whenever Maven tries to retrive Whois Ruby Gem from TorqueBox RubyGems Maven Proxy Repository it fails saying not found

**Comment by gayanW** [comment]
rubygems-relaease is not present in jruby-whois-3.5.9.2.pom.

So I had to manually add http://rubygems-proxy.torquebox.org/releases as an repository to my pom.xml
