### ISSUE TITLE
Broader Scoping

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/jruby-whois#2]
Currently the `jruby-whois.rb` script only checks for `United Kingdom` and `UK`. It doesn't check for differing cases (e.g. `UNITED KINGDOM`) or `Great Britain`, `GB`, etc.

**Comment by anjackson** [comment]
Current logic is:
```
if r.parser.registrant_contacts[0].country == "United Kingdom"
   isUK = true
end
  
if r.parser.registrant_contacts[0].country_code == "UK"
   isUK = true
end
```

But I think pull #3  is a good idea, so this logic will be moved upstream, into ukwa/w3act#TBA.

**Comment by anjackson** [comment]
Closing having moved tracking of this implementation upstream to ukwa/w3act#358
